### ISSUE TITLE
Error during template rendering 

### ISSUE THREAD

**Issue by Lebanon** [Wtower/django-ninecms#11]
Hello,

I'm trying to run ninecms (starter package) and I'm getting error.  I appreciate if you can give me a clue on the cause of the error.

Note that I've followed the instructions (step by step).

Follow are my settings & error.

If you need additional info, let me know.

Thank you,

Ahmad

Name 	                                Version
Admin_Bootstrapped_Plus 	0.1.1.2
Debug Toolbar 	1.4
Django 	1.8
Guardian 	1.3.2
Mptt 	0.7.4
Nine CMS 	0.5.2.2
Python 	3.4.3

In template C:\Python34\lib\site-packages\ninecms\templates\admin
![error](https://cloud.githubusercontent.com/assets/861097/11607738/977f89b4-9b64-11e5-9ae8-98b9ffc99b92.PNG)
\ninecms\index.html, error at line 84

**Comment by Wtower** [comment]
Hello and thanks for your contribution.

I see that you are using Windows. We have not yet evaluated the latest version with Windows, so this is obviously a bug of 9cms. 

It seems that the error is thrown on the Django administration index page, where the status report is generated. I can think of a couple of possible reasons why this error is thrown, probably because some status test is not OS-agnostic.

At the moment I do not have access to a Windows box unfortunately, I will evaluate it on Monday. Meanwhile, is it possible that you paste the full traceback of the error?

**Comment by Wtower** [comment]
Ok, I have identified the error in `ninecms/utils/status.py` and I am working on to releasing a new version (5.3) tomorrow.

**Comment by Wtower** [comment]
This is caused when 9cms tries to check if Imagemagick is installed. Imagemagick is used to manipulate image styles. Until tomorrow, alternatively, you can install [Imagemagick for Windows](http://www.imagemagick.org/script/binary-releases.php#windows).

**Comment by Lebanon** [comment]
George,

Thank you for the update.  Looking forward for the new version.

Regards,

Ahmad

**Comment by Wtower** [comment]
In order to get the fix locally, you can:

    pip uninstall django-ninecms

And then

    pip install git+https://github.com/Wtower/django-ninecms.git

I am still waiting for a small change before releasing officially v0.5.3, which will probably happen in the day or tomorrow.

Thanks again for the contribution!

**Comment by Wtower** [comment]
New version 0.5.3 available at [PyPi](https://pypi.python.org/pypi?:action=pkg_edit&name=django-ninecms)

    pip install -U django-ninecms

**Comment by Wtower** [comment]
There has been a regression, fixed with new release 0.5.3.1 available at PyPi. This should be ok now.
